sudo: false
language: ruby

before_install: gem i bundler -v '<2'

rvm:
  - 2.6.2
  - 2.5.5

gemfile:
  - gemfiles/rails_60.gemfile
  - gemfiles/rails_52.gemfile
  - gemfiles/rails_51.gemfile
  - gemfiles/rails_50.gemfile
  - gemfiles/rails_42.gemfile
