language: ruby

before_install:
  - "ruby -e 'exit RUBY_VERSION.to_f >= 2.7' && gem i bundler"

rvm:
  - 3.0.1
  - 2.7.3
  - 2.6.7

gemfile:
  - gemfiles/rails_61.gemfile
  - gemfiles/rails_60.gemfile

matrix:
  include:
    - rvm: ruby-head
      gemfile: gemfiles/rails_edge.gemfile

    - rvm: 2.7.3
      gemfile: gemfiles/rails_edge.gemfile

    - rvm: 2.6.7
      gemfile: gemfiles/rails_52.gemfile
    - rvm: 2.6.7
      gemfile: gemfiles/rails_51.gemfile
    - rvm: 2.6.7
      gemfile: gemfiles/rails_50.gemfile
    - rvm: 2.6.7
      gemfile: gemfiles/rails_42.gemfile

    - rvm: 2.5.9
      gemfile: gemfiles/rails_52.gemfile
    - rvm: 2.5.9
      gemfile: gemfiles/rails_42.gemfile

  allow_failures:
    - rvm: ruby-head
    - gemfile: gemfiles/rails_edge.gemfile
